### PR TITLE
Angular 15 support

### PR DESCRIPTION
**Pull request by msgoloborodov**
Update Dependencies to Angular v15

### CODE REVIEW

**Comment by wawyed** [comment]
Thank you, I'll have a look.

**Comment by wawyed** [comment]
Are you able to create a PR for angulay-hybrid as well?

**Comment by msgoloborodov** [comment]
> Are you able to create a PR for angulay-hybrid as well?

Yes, I'll create. Can you release version 11.0.0 (npm run release) ?

**Comment by wawyed** [comment]
Done :)

**Pull request merged**
