### PR TITLE
Add Angular v8 downstream test

### PR DESCRIPTION
**Pull request by oliverguenther**
This adds a Angular 8.0.0 downstream test object. Locally I had to run `yarn config set ignore-engines true` due to the following engine policy: chokidar > upath . Requires a bump (cf. https://github.com/anodynos/upath/issues/14)

### CODE REVIEW

**Comment by oliverguenther** [comment]
The test appears to run through fine, but still  marked as failure: `Done. Your build exited with 1.`

**Comment by dlq84** [comment]
Excuse my noobish question, but could that just a hickup on travis' part? What happens if you trigger the build again, if that's possible?

**Comment by jpike88** [comment]
hey guys are we going to see more movements on this?

**Comment by oliverguenther** [comment]
@dlq84 I triggered it again after the first failure but that seems persistent. No idea what's causing it so far

**Comment by christopherthielen** [comment]
I merged this branch via #553

I don't quite understand how there are two pull requests, but I think this is complete now

**Pull request closed without merging**
