### PR TITLE
Updated to also support RxJS 7.

### PR DESCRIPTION
**Pull request by penfold**
@christopherthielen  I didn't get the downsteam tests to run. It feels like an environment issue, but I can't see how to resolve it.

```
Compiling @uirouter/angular : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
√ Browser application bundle generation complete.
√ Browser application bundle generation complete.
- Generating ES5 bundles for differential loading...
√ ES5 bundle generation complete.
- Copying assets...
√ Copying assets complete.
- Generating index html...
√ Index html generation complete.
C:\Users\paul\AppData\Local\Temp\tmp-3008-jkF2X3qBzwqi\.downstream_cache\angular12\node_modules\.bin\serve:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### CODE REVIEW

**Comment by penfold** [comment]
See https://github.com/ui-router/rx/pull/490 to allow rx to use newer RxJS.

**Comment by penfold** [comment]
@christopherthielen Please could you release a new NPM package of rx and I'll update this PR?

**Comment by christopherthielen** [comment]
released `@uirouter/rx` v1.0.0

**Comment by penfold** [comment]
@christopherthielen Would you consider a separate PR that would mean that the new version would be targeted at only ng13? This would allow us to enable partial compilation.

At the same time, we could bump dependencies like typescript?

I'm suggesting that this would be a separate/future release from these minimal changes to allow people to upgrade to ng13.

**Pull request closed without merging**
