### PR TITLE
remove ANALYZE_FOR_ENTRY_COMPONENTS

### LINKED ISSUE #981: Breaks when building with Angular 16
`ANALYZE_FOR_ENTRY_COMPONENTS` is deprecated since angular 9 and has been removed in angular 16. Please update this lib to handle angular 16, by first removing that variable from use.

Build error:
```./node_modules/@uirouter/angular/fesm2020/uirouter-angular.mjs:1410:13-41 - Error: export 'ANALYZE_FOR_ENTRY_COMPONENTS' (imported as 'ANALYZE_FOR_ENTRY_COMPONENTS') was not found in '@angular/core' (possible exports: ANIMATION_MODULE_TYPE, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER, ApplicationInitStatus, ApplicationModule, ApplicationRef, Attribute, COMPILER_OPTIONS, CSP_NONCE, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy, ChangeDetectorRef, Compiler, CompilerFactory, Component, ComponentFactory, ComponentFactoryResolver, ComponentR.......```

### PR DESCRIPTION
**Pull request by jpike88**
fixes #981

### CODE REVIEW

**Comment by jpike88** [comment]
@wawyed this allows the library to be compatible with angular 16, and I've tested it, seems to work. Pls merge when you get a chance

**Comment by jpike88** [comment]
@wawyed would appreciate your timely attention on this, thankyou

**Comment by jpike88** [comment]
or are we going to wait till 16 is actually out? this will be a breaking change I guess so maybe best to wait

**Comment by wawyed** [comment]
Will have a look when I get some time. Thank you :)

**Comment by wawyed** [comment]
Hi, I fixed the downstream tests in the main branch. You might need to rebase your fork. @jpike88

**Comment by jpike88** [comment]
done

**Pull request merged**
